@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":GameBookParser" as GameBookParser LOGIC_COLOR
participant ":EditCommandParser" as EditCommandParser LOGIC_COLOR
participant "e:EditCommand" as EditCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box


box Model MODEL_COLOR_T1
participant ":ModelManager" as Model MODEL_COLOR
end box

box Storage STORAGE_COLOR_T1
participant ":StorageManager" as StorageManager STORAGE_COLOR
end box

[-> LogicManager : execute("edit 1 /g Mahjong")
activate LogicManager

LogicManager -> GameBookParser : parseCommand("edit 1 /g Mahjong", true)
activate GameBookParser

create EditCommandParser
GameBookParser -> EditCommandParser
activate EditCommandParser

EditCommandParser --> GameBookParser
deactivate EditCommandParser

GameBookParser -> EditCommandParser : parse("1 /g Mahjong")
activate EditCommandParser

create EditCommand
EditCommandParser -> EditCommand
activate EditCommand

EditCommand --> EditCommandParser : e
deactivate EditCommand

EditCommandParser --> GameBookParser : e
deactivate EditCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
EditCommandParser -[hidden]-> GameBookParser
destroy EditCommandParser

GameBookParser --> LogicManager : e
deactivate GameBookParser

LogicManager -> EditCommand : execute()
activate EditCommand

EditCommand -> Model : setGameEntry(target, edited)
activate Model

Model --> EditCommand
deactivate Model

create CommandResult
EditCommand -> CommandResult
activate CommandResult

CommandResult --> EditCommand
deactivate CommandResult

EditCommand --> LogicManager : result
deactivate EditCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
EditCommand -[hidden]-> LogicManager
destroy EditCommand

LogicManager -> StorageManager : saveGameBook(gameBook)
activate StorageManager

StorageManager --> LogicManager
deactivate StorageManager

[<--LogicManager
deactivate LogicManager
@enduml
