@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyGameBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class GameBook
Class ReadOnlyGameBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Class UniqueGameEntryList
Class GameEntry
Class GameType
Class Amount
Class StartAmount
Class EndAmount
Class DatePlayed
Class Duration
Class Location
Class Tag

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

GameBook .up.|> ReadOnlyGameBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyGameBook
ModelManager -left-> "1" GameBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

StartAmount -up-|> Amount
EndAmount -up-|> Amount

GameBook *--> "1" UniqueGameEntryList
UniqueGameEntryList --> "~* all" GameEntry
GameEntry *--> GameType
GameEntry *--> StartAmount
GameEntry *--> EndAmount
GameEntry *--> DatePlayed
GameEntry *--> Duration
GameEntry *--> Location
GameEntry *--> "*" Tag

GameType -[hidden]right-> StartAmount
StartAmount -[hidden]right-> EndAmount
EndAmount -[hidden]right-> DatePlayed


ModelManager -->"~* filtered" GameEntry
@enduml