@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyGameBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class GameBook
Class ReadOnlyGameBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Class GameEntryList
Class GameEntry
Class GameType
Class Amount
Class StartAmount
Class EndAmount
Class DatePlayed
Class Duration
Class Location
Class Tag
Class Average
Class Median

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Class Ui #1D8900

GameBook .up.|> ReadOnlyGameBook
Ui .right.> Average
Ui .right.> Median
Average .right-> GameEntryList
Median .right-> GameEntryList

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyGameBook
ModelManager -left-> "1" GameBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

StartAmount -up-|> Amount
EndAmount -up-|> Amount

GameBook *--> "1" GameEntryList
GameEntryList --> "~* all" GameEntry
GameEntry *--> GameType
GameEntry *--> StartAmount
GameEntry *--> EndAmount
GameEntry *--> DatePlayed
GameEntry *--> Duration
GameEntry *--> Location
GameEntry *--> "*" Tag

GameType -[hidden]right-> StartAmount
StartAmount -[hidden]right-> EndAmount
EndAmount -[hidden]right-> DatePlayed


ModelManager -->"~* filtered" GameEntry
@enduml
