@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "GameBook Storage" #F4F6F6{
Interface GameBookStorage <<Interface>>
Class JsonGameBookStorage
Class JsonSerializableGameBook
Class JsonAdaptedGameEntry
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" GameBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> GameBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonGameBookStorage .up.|> GameBookStorage
JsonGameBookStorage ..> JsonSerializableGameBook
JsonSerializableGameBook --> "*" JsonAdaptedGameEntry
JsonAdaptedGameEntry --> "*" JsonAdaptedTag

@enduml
