@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classFontSize 17
skinparam nodesep 10

skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class ResultDisplay
Class ClearWindow
Class CommandNoteListPanel
Class CommandNoteCard
Class GameEntryListPanel
Class GameEntryCard
Class StatusBarFooter
Class CommandBox
Class StatsPanel
Class GraphPanel
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside .right.> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" ClearWindow
MainWindow *-down-> "1" GameEntryListPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow *-down-> "1" CommandNoteListPanel
MainWindow *-down-> "1" StatsPanel
MainWindow *-down-> "1" GraphPanel

GameEntryListPanel -down-> "*" GameEntryCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
ClearWindow --|> UiPart
CommandBox --|> UiPart
GameEntryListPanel --|> UiPart
GameEntryCard --left|> UiPart
StatusBarFooter --|> UiPart
CommandNoteListPanel --|> UiPart
CommandNoteCard -|> UiPart
StatsPanel --|> UiPart
GraphPanel --|> UiPart

CommandNoteListPanel -- CommandNoteCard
GameEntryCard ..> Model
StatsPanel ..> Model
GraphPanel ..> Model
UiManager -up-> Logic
MainWindow -up-> Logic


MainWindow -[hidden]-|> UiPart
@enduml
